# Generated by Django 5.0.4 on 2024-04-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_forumcomment_forumpost_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='date',
            field=models.DateTimeField(default='get_current_timezone'),
        ),
    ]
