# Generated by Django 5.0.4 on 2024-04-19 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_member_delete_user_alter_forumpost_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='upload_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 15, 32, 12, 499491)),
        ),
    ]
