# Generated by Django 5.0.4 on 2024-04-25 09:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_forumpost_op_alter_forumpost_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='op',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='app.member'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 3, 29, 42, 459484)),
        ),
    ]
